/**
 * ContentStore — catalogs files generated by agents in their output directories.
 *
 * Files in each agent's workspace/output/ (or persona.outputDir) are indexed
 * on demand when `list()` is called. No filesystem watching is required.
 */

import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { readdir, stat } from 'node:fs/promises';
import { extname, isAbsolute, join } from 'node:path';
import type { Config } from '../core/config/schema.js';
import { createLogger } from '../core/logger.js';

const logger = createLogger('gateway:content-store');

export type ContentItemType = 'image' | 'video' | 'audio' | 'file';

export interface ContentItem {
  /** Stable ID derived from agentId + relative path. */
  id: string;
  agentId: string;
  /** Filename shown to the user. */
  name: string;
  /** Absolute path on the host filesystem. */
  filePath: string;
  mimeType: string;
  type: ContentItemType;
  /** File size in bytes. */
  size: number;
  /** Unix ms timestamp. */
  createdAt: number;
}

// ── MIME / type helpers ───────────────────────────────────────────────────────

const EXT_MIME: Record<string, string> = {
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.html': 'text/html',
  '.htm': 'text/html',
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
  '.mov': 'video/quicktime',
  '.mp3': 'audio/mpeg',
  '.wav': 'audio/wav',
  '.ogg': 'audio/ogg',
  '.doc': 'application/msword',
  '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.pdf': 'application/pdf',
  '.ppt': 'application/vnd.ms-powerpoint',
  '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.txt': 'text/plain',
  '.md': 'text/markdown',
  '.json': 'application/json',
  '.csv': 'text/csv',
  '.xls': 'application/vnd.ms-excel',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.zip': 'application/zip',
};

function mimeForExt(ext: string): string {
  return EXT_MIME[ext.toLowerCase()] ?? 'application/octet-stream';
}

function typeForMime(mime: string): ContentItemType {
  if (mime.startsWith('image/')) return 'image';
  if (mime.startsWith('video/')) return 'video';
  if (mime.startsWith('audio/')) return 'audio';
  return 'file';
}

function makeId(agentId: string, filePath: string): string {
  return createHash('sha256').update(`${agentId}:${filePath}`).digest('base64url');
}

function makeLegacyId(agentId: string, filePath: string): string {
  return Buffer.from(`${agentId}:${filePath}`).toString('base64url').slice(0, 24);
}

async function collectItemsForDir(
  dir: string,
  agentId: string,
  maxDepth: number,
  seenPaths: Set<string>,
): Promise<ContentItem[]> {
  if (!existsSync(dir)) {
    return [];
  }

  const items: ContentItem[] = [];
  const discovered = await scanDir(dir, 0, maxDepth);
  for (const { filePath, name } of discovered) {
    if (seenPaths.has(filePath)) {
      continue;
    }
    seenPaths.add(filePath);
    const ext = extname(name);
    const mime = mimeForExt(ext);
    const fileStat = await stat(filePath);
    items.push({
      id: makeId(agentId, filePath),
      agentId,
      name,
      filePath,
      mimeType: mime,
      type: typeForMime(mime),
      size: fileStat.size,
      createdAt: fileStat.birthtimeMs || fileStat.mtimeMs,
    });
  }
  return items;
}

// ── ContentStore ──────────────────────────────────────────────────────────────

export class ContentStore {
  private getConfig: () => Config;

  constructor(getConfig: () => Config) {
    this.getConfig = getConfig;
  }

  /**
   * Scan all configured agent output directories and return a flat list of files.
   * Deep-scans two levels into subdirectories so mirrored skill artifacts under
   * output/skill-artifacts/<skill>/... are indexed automatically.
   */
  async list(): Promise<ContentItem[]> {
    const cfg = this.getConfig();
    const items: ContentItem[] = [];

    for (const agentCfg of cfg.agents) {
      const workspace = agentCfg.workspace ?? cfg.defaults.workspace;
      if (!workspace) continue;

      const outputDir = agentCfg.persona?.outputDir ?? 'output';
      const absOutput = isAbsolute(outputDir) ? outputDir : join(workspace, outputDir);
      const seenPaths = new Set<string>();

      try {
        items.push(...(await collectItemsForDir(absOutput, agentCfg.id, 2, seenPaths)));
        // Also index files written directly into the workspace root. Some skills
        // copy their final artifact to the current workspace instead of output/.
        items.push(...(await collectItemsForDir(workspace, agentCfg.id, 0, seenPaths)));
      } catch (err) {
        logger.warn('ContentStore scan error', { agentId: agentCfg.id, error: String(err) });
      }
    }

    // Sort newest first
    items.sort((a, b) => b.createdAt - a.createdAt);
    return items;
  }

  /** Find a single item by id. */
  async get(id: string): Promise<ContentItem | null> {
    const all = await this.list();
    return (
      all.find((item) => item.id === id || makeLegacyId(item.agentId, item.filePath) === id) ?? null
    );
  }
}

/** Recursively list files one level deep under dir. */
async function scanDir(
  dir: string,
  depth = 0,
  maxDepth = 1,
): Promise<{ filePath: string; name: string }[]> {
  if (depth > maxDepth) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  const results: { filePath: string; name: string }[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory() && depth < maxDepth) {
      results.push(...(await scanDir(full, depth + 1, maxDepth)));
    } else if (entry.isFile()) {
      results.push({ filePath: full, name: entry.name });
    }
  }
  return results;
}
