/**
 * ContentStore — catalogs files generated by agents in their output directories.
 *
 * Files in each agent's workspace/output/ (or persona.outputDir) are indexed
 * on demand when `list()` is called. No filesystem watching is required.
 */

import { existsSync } from 'node:fs';
import { readdir, stat } from 'node:fs/promises';
import { extname, join } from 'node:path';
import type { Config } from '../core/config/schema.js';
import { createLogger } from '../core/logger.js';

const logger = createLogger('gateway:content-store');

export type ContentItemType = 'image' | 'video' | 'audio' | 'file';

export interface ContentItem {
  /** Stable ID derived from agentId + relative path. */
  id: string;
  agentId: string;
  /** Filename shown to the user. */
  name: string;
  /** Absolute path on the host filesystem. */
  filePath: string;
  mimeType: string;
  type: ContentItemType;
  /** File size in bytes. */
  size: number;
  /** Unix ms timestamp. */
  createdAt: number;
}

// ── MIME / type helpers ───────────────────────────────────────────────────────

const EXT_MIME: Record<string, string> = {
  '.png': 'image/png',  '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',  '.webp': 'image/webp', '.svg': 'image/svg+xml',
  '.mp4': 'video/mp4',  '.webm': 'video/webm', '.mov': 'video/quicktime',
  '.mp3': 'audio/mpeg', '.wav': 'audio/wav',   '.ogg': 'audio/ogg',
  '.pdf': 'application/pdf',
  '.txt': 'text/plain', '.md': 'text/markdown',
  '.json': 'application/json',
  '.csv': 'text/csv',
  '.zip': 'application/zip',
};

function mimeForExt(ext: string): string {
  return EXT_MIME[ext.toLowerCase()] ?? 'application/octet-stream';
}

function typeForMime(mime: string): ContentItemType {
  if (mime.startsWith('image/')) return 'image';
  if (mime.startsWith('video/')) return 'video';
  if (mime.startsWith('audio/')) return 'audio';
  return 'file';
}

function makeId(agentId: string, filePath: string): string {
  return Buffer.from(`${agentId}:${filePath}`).toString('base64url').slice(0, 24);
}

// ── ContentStore ──────────────────────────────────────────────────────────────

export class ContentStore {
  private getConfig: () => Config;

  constructor(getConfig: () => Config) {
    this.getConfig = getConfig;
  }

  /**
   * Scan all configured agent output directories and return a flat list of files.
   * Deep-scans one level into subdirectories.
   */
  async list(): Promise<ContentItem[]> {
    const cfg = this.getConfig();
    const items: ContentItem[] = [];

    for (const agentCfg of cfg.agents) {
      const workspace = agentCfg.workspace ?? cfg.defaults.workspace;
      if (!workspace) continue;

      const outputDir = agentCfg.persona?.outputDir ?? 'output';
      const absOutput = outputDir.startsWith('/')
        ? outputDir
        : join(workspace, outputDir);

      if (!existsSync(absOutput)) continue;

      try {
        const discovered = await scanDir(absOutput);
        for (const { filePath, name } of discovered) {
          const ext = extname(name);
          const mime = mimeForExt(ext);
          const s = await stat(filePath);
          items.push({
            id: makeId(agentCfg.id, filePath),
            agentId: agentCfg.id,
            name,
            filePath,
            mimeType: mime,
            type: typeForMime(mime),
            size: s.size,
            createdAt: s.birthtimeMs || s.mtimeMs,
          });
        }
      } catch (err) {
        logger.warn('ContentStore scan error', { agentId: agentCfg.id, error: String(err) });
      }
    }

    // Sort newest first
    items.sort((a, b) => b.createdAt - a.createdAt);
    return items;
  }

  /** Find a single item by id. */
  async get(id: string): Promise<ContentItem | null> {
    const all = await this.list();
    return all.find((item) => item.id === id) ?? null;
  }
}

/** Recursively list files one level deep under dir. */
async function scanDir(
  dir: string,
  depth = 0,
): Promise<{ filePath: string; name: string }[]> {
  if (depth > 1) return [];
  const entries = await readdir(dir, { withFileTypes: true });
  const results: { filePath: string; name: string }[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory() && depth === 0) {
      results.push(...(await scanDir(full, depth + 1)));
    } else if (entry.isFile()) {
      results.push({ filePath: full, name: entry.name });
    }
  }
  return results;
}
