/**
 * Soul file utilities.
 *
 * A "soul" consists of:
 *   - SOUL.md in the agent workspace — identity, personality, description (user-editable)
 *   - Inline persona config (agentflyer.json) — machine-read fields only: language, outputDir
 *
 * Layer mapping:
 *   Layer 0 — language instruction injected here (from persona.language)
 *   Layer 1 — SOUL.md loaded here via workspace.ts (semi-static, 30 s cache)
 */

import type { AgentConfig } from '../../core/config/schema.js';

// ── Inline persona → Layer 0 content ─────────────────────────────────────────

/**
 * Build the Layer 0 persona fragment.
 * Only injects the language instruction — all narrative identity/personality
 * content lives in SOUL.md (Layer 1) so config stays machine-readable.
 */
export function buildPersonaContent(cfg: AgentConfig): string {
  const lang = cfg.persona.language;
  const langLine = lang.startsWith('zh')
    ? '默认使用中文（简体）回复。除非用户使用其他语言提问，否则不要切换语言。'
    : `Default response language: ${lang}. Mirror the user's language when they write in a different one.`;
  return `## Language\n${langLine}`;
}

// ── SOUL.md template generator ────────────────────────────────────────────────

/**
 * Generate a SOUL.md template string from an agent's config.
 * Written to {workspace}/SOUL.md on first startup.
 * The file is auto-generated but fully user-editable — changes are picked
 * up within 30 s (workspace doc cache TTL).
 */
export function generateSoulMd(cfg: AgentConfig): string {
  const name = cfg.name ?? cfg.id;

  const triggersSection =
    cfg.mesh.triggers.length > 0
      ? cfg.mesh.triggers.map((t) => `- ${t}`).join('\n')
      : '<!-- 在此添加触发词让路由更精准，例如: - 搜索\n- 查资料 -->';

  const capabilitiesSection =
    cfg.mesh.capabilities.length > 0
      ? cfg.mesh.capabilities.map((c) => `- ${c}`).join('\n')
      : '<!-- 填写此 agent 擅长的能力标签，例如: - web_search\n- code -->';

  const toolsAllowNote = cfg.tools.allow
    ? `允许工具: ${cfg.tools.allow.join(', ')}`
    : '(全部工具可用，受 deny 列表约束)';

  return `# ${name} — Soul File

<!-- 此文件由 AgentFlyer 在首次启动时自动生成。可以自由编辑，修改后 30 秒内生效。 -->
<!-- Auto-generated by AgentFlyer on first launch. Edit freely — changes apply within 30 s. -->

## Identity

你是 ${name}，一个由 AgentFlyer 驱动的专业 AI 智能体。

## Description

${name} 负责处理用户或协调者智能体委派的任务，准确、高效地完成目标。

## Personality & Style

- helpful
- accurate
- concise

## Language

首选语言: ${cfg.persona.language}
规则: 默认使用上述语言回复；若用户以其他语言提问，跟随用户语言。

## Capabilities

${capabilitiesSection}

## Mesh Configuration

- Role: ${cfg.mesh.role}
- Visibility: ${cfg.mesh.visibility}
- Accepts: ${cfg.mesh.accepts.join(', ')}

## Heartbeat Triggers

${triggersSection}

## Tool Access

${toolsAllowNote}
Deny list: ${cfg.tools.deny.length > 0 ? cfg.tools.deny.join(', ') : '(none)'}
Requires approval: ${cfg.tools.approval.length > 0 ? cfg.tools.approval.join(', ') : '(none)'}

## Output Directory

${cfg.persona.outputDir} (relative to workspace, or absolute path)

---
*Agent ID: ${cfg.id} | Model: ${cfg.model ?? '(default)'}*
`;
}
