import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Worker } from 'node:worker_threads';
import { ulid } from 'ulid';
import { createLogger } from '../../core/logger.js';
import type { Message } from '../../core/types.js';

const logger = createLogger('compactor:structured');

export interface CompactionSummary {
  /** ISO timestamp of the oldest summarised message */
  from: string;
  /** ISO timestamp of the newest summarised message */
  to: string;
  /** Number of messages summarised */
  messageCount: number;
  /** Free-text summary generated by the LLM */
  narrative: string;
  /** Key facts extracted as short bullet strings */
  facts: string[];
  /** Any open tool calls / unresolved work that was in progress */
  pendingWork: string[];
}

export interface CompactionResult {
  /** Message to inject at the start of the trimmed transcript */
  summaryMessage: Message;
  /** Kept messages (recent, post-summary) */
  keptMessages: Message[];
  /** How many messages were compacted */
  compactedCount: number;
}

const COMPACTION_PROMPT = `You are a transcript compactor. Summarise the conversation history below into a compact JSON object. Output ONLY valid JSON, no markdown fences, no explanation.

Schema:
{
  "from": "<ISO timestamp of first message>",
  "to": "<ISO timestamp of last message>",
  "messageCount": <integer>,
  "narrative": "<2-6 sentence prose summary of what was discussed and accomplished>",
  "facts": ["<short fact 1>", ...],
  "pendingWork": ["<unfinished task 1>", ...]
}

Rules:
- facts: each ≤15 words, include key decisions, file paths, values, errors
- pendingWork: only items explicitly left unfinished
- narrative: plain English, past tense

Transcript to summarise:
`;

/** Build the prompt for the LLM to produce a CompactionSummary. */
export function buildCompactionPrompt(messages: Message[]): string {
  const transcript = messages
    .map((m) => {
      const role = m.role.toUpperCase();
      const content = typeof m.content === 'string' ? m.content : JSON.stringify(m.content);
      return `[${role}]: ${content}`;
    })
    .join('\n\n');
  return COMPACTION_PROMPT + transcript;
}

/**
 * Parse the LLM's JSON output into a CompactionSummary.
 * Tolerates minor LLM formatting artefacts (trailing commas, code fences).
 */
export function parseSummaryJson(raw: string): CompactionSummary {
  // Strip optional ```json ... ``` fences
  const cleaned = raw
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/\s*```\s*$/, '')
    .trim();
  try {
    return JSON.parse(cleaned) as CompactionSummary;
  } catch (err) {
    logger.warn('Failed to parse compaction JSON', { raw: raw.slice(0, 200), error: String(err) });
    // Return a minimal fallback
    return {
      from: new Date().toISOString(),
      to: new Date().toISOString(),
      messageCount: 0,
      narrative: 'Prior conversation history (parse error — content unavailable).',
      facts: [],
      pendingWork: [],
    };
  }
}

/** Convert a CompactionSummary into a system-role stub message. */
export function summaryToMessage(summary: CompactionSummary): Message {
  const facts = summary.facts.length
    ? `\n\nKey facts:\n${summary.facts.map((f) => `- ${f}`).join('\n')}`
    : '';
  const pending = summary.pendingWork.length
    ? `\n\nPending work:\n${summary.pendingWork.map((p) => `- ${p}`).join('\n')}`
    : '';

  const text = `[COMPACTED HISTORY — ${summary.messageCount} messages from ${summary.from} to ${summary.to}]\n\n${summary.narrative}${facts}${pending}`;

  return { role: 'user', content: text };
}

/**
 * Decide how many messages to keep vs compact.
 * Strategy: keep the newest `keepCount` messages; compact everything before.
 * The split is adjusted backwards to avoid breaking tool_call/tool_result pairs:
 * if the first kept message is a user message that carries tool_results,
 * the preceding assistant tool_calls would be compacted away — move the
 * boundary back until the first kept message is not a tool_result response.
 */
export function splitForCompaction(
  messages: Message[],
  keepCount: number,
): { toCompact: Message[]; toKeep: Message[] } {
  if (messages.length <= keepCount) {
    return { toCompact: [], toKeep: messages };
  }
  let splitAt = messages.length - keepCount;

  // Walk splitAt backwards until it does not point at a tool_result user message
  // (which would orphan its preceding assistant tool_calls into toCompact).
  while (splitAt > 0) {
    const msg = messages[splitAt];
    if (!msg) break;
    const isToolResultMsg =
      msg.role === 'user' &&
      Array.isArray(msg.content) &&
      (msg.content as import('../../core/types.js').MessageContent[]).some(
        (c) => c.type === 'tool_result',
      );
    if (!isToolResultMsg) break;
    splitAt--;
  }

  return {
    toCompact: messages.slice(0, splitAt),
    toKeep: messages.slice(splitAt),
  };
}

// ── Compaction worker client ────────────────────────────────────────────────

export interface CompactionWorkerConfig {
  /** Full URL to the LLM chat-completions endpoint. */
  apiUrl: string;
  apiKey: string;
  model: string;
  maxTokens?: number;
  provider: 'anthropic' | 'openai';
}

const WORKER_SCRIPT = join(
  dirname(fileURLToPath(import.meta.url)),
  '../../worker/compaction-worker.js',
);

interface PendingCompact {
  resolve: (text: string) => void;
  reject: (err: Error) => void;
}

let _worker: Worker | null = null;
const _pending = new Map<string, PendingCompact>();

const logger2 = createLogger('compactor:worker');

export function createCompactionWorker(): Worker {
  if (_worker) return _worker;
  _worker = new Worker(WORKER_SCRIPT);
  _worker.on('message', (msg: { id: string; text?: string; error?: string }) => {
    const pending = _pending.get(msg.id);
    if (!pending) return;
    _pending.delete(msg.id);
    if (msg.error) {
      pending.reject(new Error(msg.error));
    } else {
      pending.resolve(msg.text ?? '');
    }
  });
  _worker.on('error', (err) => {
    logger2.error('Compaction worker error', { error: String(err) });
    for (const [id, p] of _pending) {
      p.reject(err);
      _pending.delete(id);
    }
    _worker = null;
  });
  return _worker;
}

/**
 * Run compaction via a Worker thread using a direct fetch() call to the LLM
 * API. Returns the raw generated text (expected to be a CompactionSummary JSON).
 */
export async function runCompactionViaWorker(
  messages: Message[],
  cfg: CompactionWorkerConfig,
): Promise<string> {
  const prompt = buildCompactionPrompt(messages);
  const worker = createCompactionWorker();
  const id = ulid();
  return new Promise<string>((resolve, reject) => {
    _pending.set(id, { resolve, reject });
    worker.postMessage({
      id,
      prompt,
      api: {
        url: cfg.apiUrl,
        apiKey: cfg.apiKey,
        model: cfg.model,
        maxTokens: cfg.maxTokens,
        provider: cfg.provider,
      },
    });
  });
}
